name: 'Malakinetics '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71887
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Malakinetics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#8a0037'
    - '#323934'
    - '#776f69'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
