name: 'Malakinetics '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7723404
title: Malakinetics
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#020103'
    - '#A4A3A4'
    - '#302F31'
    - '#787678'
  brandStrength: 0.7319149
  lightness: 0.5
  saturation: 0.5510638
  rhythmicContrast: 0.75
purpose: []
