name: 'Malakinetics '
favicon: null
layout_spectrum: 0.51887
typography_spectrum: 0.7234042
title: Malakinetics
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71138804-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#020103'
    - '#A4A3A4'
    - '#302F31'
    - '#787678'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
