typography_spectrum: 0.7234042
color:
  brandColors:
    - '#FFFFFF'
    - '#020103'
    - '#A4A3A4'
    - '#302F31'
    - '#787678'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.51887
analytics:
  google: UA-71138804-1
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3a75a845-8e91-4611-a3a3-6cd66bd507aa.png
name: 'Malakinetics '
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
navigation:
  - name: Artist Statement
    id: 583a540f-5586-42f4-b5df-2daf1ea4f2ec
    type: content
  - name: Biography
    id: e544ac6b-a2d0-4fd7-a37b-e37bdb800818
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Malakinetics
purpose: []
